### PR TITLE
Simplify kernel functions

### PR DESCRIPTION
**Pull request by LudwigBoess**

### CODE REVIEW

**Review by AhmedSalih3d — APPROVED** [review]
I approve these changes I see that you have implemented it as we have been talking about.

Kernels have no neighbour value any more, and dim is used to control dimensions with 3 being the default. Allows for easy construction of kernels and defining their derivatives when related to h^dim atleast.

You also updated all the tests I see, which looks good.

A minor note is, the way of writing W you have chosen does not show in the default Julia terminal. Perhaps this should be changed?

image

**Review by AhmedSalih3d — COMMENTED** [review]
Had a look through the explanation files, looks fine

**Comment by LudwigBoess** [comment]
I can't reproduce the unicode error you see with `𝒲`. For me it works fine in the Julia REPL.
Can you try typing it out like it says with `\scrW` and then tab complete?

**Comment by AhmedSalih3d** [comment]
> I can't reproduce the unicode error you see with `𝒲`. For me it works fine in the Julia REPL.
> Can you try typing it out like it says with `\scrW` and then tab complete?

image

Seems to not work for me :)

Using Julia 1.5 with no fancy stuff, perhaps there is a error in my install.

Kind regards

**Comment by LudwigBoess** [comment]
Ah, maybe that's one of the new `utf-8` characters they allow in 1.6. 
I use 1.6 and there it works fine.
If it's ok for you I'll just leave it as is...

**Comment by AhmedSalih3d** [comment]
> Ah, maybe that's one of the new `utf-8` characters they allow in 1.6.
> I use 1.6 and there it works fine.
> If it's ok for you I'll just leave it as is...

Since we know the reason, totally fine - keep it as is!

**Pull request merged**
